version: '3'
services:
  db:
    build:
      context: ./docker/mysql
      args:
        mysql_version: ${MYSQL_VERSION}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./sql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./phpmyadmin-data:/sessions
    ports:
      - "8081:80"
    networks:
      - my-network

  webserver:
    build:
      context: ./docker/php
      args:
        php_version: ${PHP_VERSION}
    volumes:
      - ./www:/var/www/html
    ports:
      - "${PHP_PORT}:80"
    links:
      - db
    networks:
      - my-network

volumes:
  my-db:

networks:
  my-network:
    driver: bridge