version: '3'
services:
  db:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./sql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./phpmyadmin-data:/sessions
    ports:
      - "8080:80"

  webserver:
    image: php:${PHP_VERSION}
    volumes:
      - ./www:/var/www/html
    ports:
      - "${PHP_PORT}:80"
    links:
      - db
volumes:
  my-db: